Repository NREL/ssc, pull requests merged in 2020-11, with the labels that each got.

#461 Marine CBS UI enhancements
  ssc/cmod_mhk_costs.cpp
  ssc/cmod_mhk_tidal.cpp
  ssc/cmod_mhk_wave.cpp
Labels: enhancement

#479 Battery Calendar Model set to None results in Cap % > 100
  shared/lib_battery_lifetime.cpp
Labels: battery, bug

#480 Update 6par Module Model Parameter Generator
  shared/6par_solve.h
  test/shared_test/6par_solve_test.cpp
Labels: pv
