Repository NREL/ssc, pull requests merged in 2021-12, with the labels that each got.

#686 Added haf initialization to GeothermPlantAnalyzer test setup
  test/shared_test/lib_geothermal_test.h
Labels: bug

#687 Ssc 614 increase tolerance again
  test/ssc_test/cmod_battery_pvsamv1_test.cpp
Labels: bug, battery

#684 Github actions on Linux
  .github/workflows/ci.yml
Labels: enhancement

#683 Fix sam 802 forecast errors
  shared/lib_battery_dispatch_automatic_btm.cpp
  shared/lib_battery_dispatch_automatic_btm.h
  ssc/cmod_battery.cpp
  ssc/cmod_battery.h
  ssc/cmod_pvsamv1.cpp
  test/ssc_test/cmod_battery_pvsamv1_test.cpp
Labels: bug, battery

#691 GitHub Actions working on Mac build
  .github/workflows/ci.yml
Labels: enhancement

#697 Update build badge and release number in citation
  README.md
Labels: enhancement
