Repository NREL/ssc, pull requests merged in 2021-04, with the labels that each got.

#559 Contour plots of system power generated for summary page
  ssc/cmod_battery.cpp
  ssc/cmod_battwatts.cpp
  ssc/cmod_biomass.cpp
  ssc/cmod_fuelcell.cpp
  ssc/cmod_generic_system.cpp
  ssc/cmod_geothermal.cpp
  ssc/cmod_hcpv.cpp
  ssc/cmod_linear_fresnel_dsg_iph.cpp
  ssc/cmod_pvsamv1.cpp
  ssc/cmod_pvwattsv7.cpp
  ssc/cmod_swh.cpp
  ssc/cmod_tcsdirect_steam.cpp
  ssc/cmod_tcsdish.cpp
  ssc/cmod_tcsgeneric_solar.cpp
  ssc/cmod_tcsiscc.cpp
  ssc/cmod_tcslinear_fresnel.cpp
  ssc/cmod_tcsmolten_salt.cpp
  ssc/cmod_tcsmslf.cpp
  ssc/cmod_tcstrough_empirical.cpp
  ssc/cmod_tcstrough_physical.cpp
  ssc/cmod_trough_physical.cpp
  ssc/cmod_trough_physical_iph.cpp
  ssc/cmod_windpower.cpp
  ssc/common.cpp
  ssc/common.h
Labels: enhancement

#556 Made battery computed variables inouts for viewing in results
  ssc/cmod_battery.cpp
Labels: battery, bug

#560 ensure num_tiers is enforced for the first tier of each month
  shared/lib_utility_rate_equations.cpp
Labels: bug

#567 Add error checks for when PV module dimensions are 0
  shared/lib_irradproc.cpp
  ssc/cmod_pvsamv1.cpp
Labels: pv

#570 Remove fuelcell and battery outputs from cases without those systems
  ssc/cmod_cashloan.cpp
  ssc/cmod_equpartflip.cpp
  ssc/cmod_fuelcell.cpp
  ssc/cmod_host_developer.cpp
  ssc/cmod_levpartflip.cpp
  ssc/cmod_merchantplant.cpp
  ssc/cmod_pvsamv1.cpp
  ssc/cmod_saleleaseback.cpp
  ssc/cmod_singleowner.cpp
  ssc/common.cpp
Labels: battery, bug
