Repository NREL/ssc, pull requests merged in 2022-02, with the labels that each got.

#754 Add weather file column headings from pvlib
  shared/lib_weatherfile.cpp
Labels: requires SAM Help revision

#756 Confirm net means net
  ssc/cmod_cashloan.cpp
  ssc/cmod_communitysolar.cpp
  ssc/cmod_equpartflip.cpp
  ssc/cmod_host_developer.cpp
  ssc/cmod_ippppa.cpp
  ssc/cmod_levpartflip.cpp
  ssc/cmod_merchantplant.cpp
  ssc/cmod_saleleaseback.cpp
  ssc/cmod_singleowner.cpp
  ssc/cmod_thirdpartyownership.cpp
  ssc/common_financial.cpp
Labels: financial

#730 Update cmod_windpower error warnings for failed user-defined wind turbine powercurves
  ssc/cmod_windpower.cpp
  ssc/cmod_windpower_eqns.cpp
Labels: bug, wind

#751 Battery temperature array error message
  ssc/cmod_battery.cpp
Labels: bug, battery

#741 745 zero load during grid outage
  shared/lib_battery_powerflow.cpp
  ssc/cmod_battery.cpp
  ssc/cmod_battwatts.cpp
  ssc/cmod_grid.cpp
  ssc/cmod_pvsamv1.cpp
  test/shared_test/lib_battery_powerflow_test.cpp
Labels: enhancement

#759 Fix MSLF partial sequential defocus bug
  tcs/sam_mw_lf_type262_salt.cpp
Labels: bug

#760 Fix MSLF partial sequential defocus bug
  tcs/sam_mw_lf_type262_salt.cpp
Labels: bug

#763 NMC/Gr bug fix & Switch to cycle_counts vector
  shared/lib_battery_lifetime_calendar_cycle.cpp
  shared/lib_battery_lifetime_calendar_cycle.h
  shared/lib_battery_lifetime_nmc.cpp
  shared/lib_battery_lifetime_nmc.h
  shared/lib_util.cpp
  shared/lib_util.h
  shared/logger.cpp
  ssc/cmod_battery_stateful.cpp
  ssc/ssc_equations.h
  test/input_cases/battery_nmc_life/lifetime_validation_cell_1.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_10.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_11.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_2.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_3.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_4.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_5.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_6.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_7.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_8.json
  test/input_cases/battery_nmc_life/lifetime_validation_cell_9.json
  test/shared_test/lib_battery_lifetime_lmolto_test.cpp
  test/shared_test/lib_battery_lifetime_nmc_test.cpp
  test/shared_test/lib_battery_lifetime_test.cpp
  test/shared_test/lib_battery_test.cpp
  test/ssc_test/cmod_battery_pvsamv1_test.cpp
  test/ssc_test/cmod_battery_stateful_test.cpp
  test/ssc_test/cmod_battwatts_test.cpp
  test/ssc_test/save_as_JSON_test.cpp
Labels: battery

#767 Remove crit_load input from PVWatts battery ReOpt calls
  ssc/cmod_pvsamv1_eqns.cpp
  ssc/cmod_pvsamv1_eqns.h
Labels: bug
