Repository NREL/ssc, pull requests merged in 2022-10, with the labels that each got.

#880 add capability for AC connected battery to charge from fuel cell
  shared/lib_battery_dispatch.cpp
  test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp
Labels: enhancement, battery

#881 Fix battery dispatch for retail rate electricity purchases.
  ssc/cmod_utilityrate5.cpp
  ssc/common.cpp
Labels: bug, battery

#882 fix index bug for price signals dispatch
  shared/lib_utility_rate_equations.cpp
  test/input_cases/shared_rate_data.cpp
  test/input_cases/shared_rate_data.h
  test/shared_test/lib_utility_rate_test.cpp
Labels: bug, battery

#877 Ssc 865 improve dispatch
  shared/lib_battery_dispatch_automatic_fom.cpp
  ssc/cmod_battery.cpp
  test/shared_test/lib_battery_dispatch_automatic_fom_test.cpp
  test/ssc_test/cmod_battery_pvsamv1_test.cpp
Labels: bug, battery

#885 PV angle var table checks
  shared/lib_pv_io_manager.cpp
  ssc/cmod_pvsamv1.cpp
  test/input_cases/pvsamv1_common_data.cpp
  test/input_cases/pvyield_common_data.h
Labels: bug

#892 Fix buffer overflow and remove redundant albedo checks
  shared/lib_pv_io_manager.cpp
Labels: bug

#896 Revert changes to POA irradiance reductions
  shared/lib_pvshade.cpp
  test/input_json/TechnologyModels/pvwattsv8/dc_ac_ratio_0.02_PVWatts_Single_Owner_cmod_pvwattsv8_outputs.json
  test/input_json/TechnologyModels/pvwattsv8/dc_ac_ratio_0.5_PVWatts_Single_Owner_cmod_pvwattsv8_outputs.json
  test/input_json/TechnologyModels/pvwattsv8/dc_ac_ratio_1.5_PVWatts_Single_Owner_cmod_pvwattsv8_outputs.json
  test/input_json/TechnologyModels/pvwattsv8/dc_ac_ratio_10_PVWatts_Single_Owner_cmod_pvwattsv8_outputs.json
  test/input_json/TechnologyModels/pvwattsv8/dc_ac_ratio_1_PVWatts_Single_Owner_cmod_pvwattsv8_outputs.json
  test/input_json/TechnologyModels/pvwattsv8/dc_ac_ratio_2_PVWatts_Single_Owner_cmod_pvwattsv8_outputs.json
  test/ssc_test/cmod_pvsamv1_test.cpp
  test/ssc_test/cmod_pvwattsv5_test.cpp
  test/ssc_test/cmod_pvwattsv7_test.cpp
  test/ssc_test/cmod_pvwattsv8_test.cpp
  test/ssc_test/cmod_pvyield_test.cpp
  test/ssc_test/save_as_JSON_test.cpp
Labels: bug

#898 Bifacial fixes
  shared/lib_pv_io_manager.cpp
  ssc/cmod_pvsamv1.cpp
Labels: bug

#878 Updated loss factor calculations for lifetime, subhourly options;
  shared/lib_geothermal.cpp
  shared/lib_geothermal.h
  ssc/cmod_etes_electric_resistance.cpp
  ssc/cmod_etes_ptes.cpp
  ssc/cmod_generic_system.cpp
  ssc/cmod_geothermal.cpp
  ssc/cmod_linear_fresnel_dsg_iph.cpp
  ssc/cmod_pvsamv1.cpp
  ssc/cmod_pvwattsv5.cpp
  ssc/cmod_pvwattsv7.cpp
  ssc/cmod_pvwattsv8.cpp
  ssc/cmod_swh.cpp
  ssc/cmod_tcsdish.cpp
  ssc/cmod_tcsgeneric_solar.cpp
  ssc/cmod_tcsmolten_salt.cpp
  ssc/cmod_tcstrough_physical.cpp
  ssc/cmod_trough_physical.cpp
  ssc/cmod_trough_physical_iph.cpp
  ssc/common.cpp
  ssc/common.h
  test/shared_test/lib_geothermal_test.h
  test/ssc_test/cmod_pvsamv1_test.cpp
Labels: new feature

#897 PV temperature updates in ssc
  shared/lib_cec6par.cpp
  shared/lib_cec6par.h
  shared/lib_pv_io_manager.cpp
  ssc/cmod_pvsamv1.cpp
  test/ssc_test/cmod_pvsamv1_test.cpp
Labels: pv

#890 Me Wave model updates
  ssc/cmod_battery.cpp
  ssc/cmod_grid.cpp
  ssc/cmod_mhk_wave.cpp
  ssc/cmod_singleowner.cpp
  ssc/cmod_wavefile.cpp
  ssc/common.cpp
Labels: new feature, mhk

#886 GETEM SAM Updates
  shared/lib_geothermal.cpp
  shared/lib_geothermal.h
  ssc/cmod_geothermal.cpp
  ssc/cmod_geothermal_costs.cpp
  test/input_cases/geothermal_common_data.h
  test/input_cases/geothermal_costs_common_data.h
  test/shared_test/lib_geothermal_test.h
  test/ssc_test/cmod_geothermal_costs_test.cpp
  test/ssc_test/cmod_geothermal_test.cpp
Labels: enhancement

#899 784 fix ac dc powers
  code_attic/lib_power_electronics_old.h
  shared/CMakeLists.txt
  shared/lib_battery_dispatch.cpp
  shared/lib_battery_dispatch.h
  shared/lib_battery_dispatch_manual.cpp
  shared/lib_battery_powerflow.cpp
  shared/lib_battery_powerflow.h
  shared/lib_power_electronics.h
  ssc/cmod_battery.cpp
  ssc/cmod_battery.h
  test/shared_test/lib_battery_dispatch_manual_test.cpp
  test/shared_test/lib_battery_powerflow_test.cpp
  test/shared_test/lib_battery_powerflow_test.h
  test/shared_test/lib_resilience_test.cpp
  test/ssc_test/cmod_battery_pvsamv1_test.cpp
Labels: bug, battery

#900 SAM 658 restore pv priority manual dispatch
  shared/lib_battery_dispatch_manual.cpp
  shared/lib_battery_dispatch_manual.h
  shared/lib_battery_powerflow.cpp
  shared/lib_battery_powerflow.h
  ssc/cmod_battery.cpp
  ssc/cmod_battery.h
  test/shared_test/lib_battery_dispatch_manual_test.cpp
  test/shared_test/lib_battery_powerflow_test.cpp
Labels: enhancement, battery, requires SAM Help revision

#904 Update pv smoothing battery soc at the end of the step
  shared/lib_battery_dispatch_pvsmoothing_fom.cpp
Labels: bug, battery

#908 Add weather file header data to outputs Fix #453
  ssc/cmod_pvsamv1.cpp
  ssc/cmod_pvwattsv8.cpp
  ssc/cmod_windpower.cpp
Labels: enhancement, requires SAM Help revision
