Repository NREL/ssc, pull requests merged in 2022-09, with the labels that each got.

#859 Task3 TES modularity
  ssc/CMakeLists.txt
  ssc/cmod_csp_subcomponent.cpp
  ssc/cmod_etes_electric_resistance.cpp
  ssc/cmod_etes_ptes.cpp
  ssc/cmod_tcsmolten_salt.cpp
  ssc/cmod_tcstrough_physical_csp_solver.cpp
  ssc/cmod_trough_physical.cpp
  ssc/cmod_trough_physical_iph.cpp
  ssc/sscapi.cpp
  tcs/csp_solver_pc_Rankine_indirect_224.cpp
  tcs/csp_solver_stratified_tes.cpp
  tcs/csp_solver_stratified_tes.h
  tcs/csp_solver_two_tank_tes.cpp
  tcs/csp_solver_two_tank_tes.h
  tcs/sam_mw_trough_type251.cpp
  test/shared_test/lib_csp_tes_test.cpp
  test/shared_test/lib_csp_tes_test.h
  test/ssc_test/csp_common_test.h
Labels: enhancement, csp

#868 Cmod utilityrateforecast
  shared/lib_battery_dispatch_automatic_btm.cpp
  shared/lib_utility_rate.h
  shared/lib_utility_rate_equations.cpp
  shared/lib_utility_rate_equations.h
  ssc/CMakeLists.txt
  ssc/cmod_utilityrateforecast.cpp
  ssc/cmod_utilityrateforecast.h
  ssc/sscapi.cpp
Labels: enhancement

#869 Generalizing CSP TES variable names
  tcs/csp_solver_core.cpp
  tcs/csp_solver_core.h
  tcs/csp_solver_two_tank_tes.cpp
  tcs/csp_solver_two_tank_tes.h
  test/shared_test/lib_csp_tes_test.cpp
Labels: enhancement

#875 Fix number of wells flow rate calculations for binary plants
  shared/lib_geothermal.cpp
Labels: bug

#879 add ts_hour to ac wiring loss line
  ssc/cmod_pvsamv1.cpp
Labels: bug, pv
