Repository NREL/ssc, pull requests merged in 2022-11, with the labels that each got.

#912 Fix annual total loss percent output value
  ssc/cmod_pvsamv1.cpp
Labels: bug

#925 Ssc 923 use prod factors
  ssc/cmod_pvsamv1_eqns.cpp
  test/ssc_test/cmod_pvsamv1_test.cpp
Labels: enhancement, battery

#926 add units and metadata for utility rates inputs
  ssc/common.cpp
Labels: enhancement, utility rate

#929 update community solar npv to use annual benefits, not cumulative
  ssc/cmod_communitysolar.cpp
  test/input_json/FinancialModels/communitysolar/2022.08.08_develop_branch_PVWatts_Community_Solar_cmod_communitysolar_outputs.json
Labels: bug, financial

#927 Update pvsamv1, pvwattsv8 var tables
  ssc/cmod_pvsamv1.cpp
  ssc/cmod_pvwattsv8.cpp
  test/ssc_test/cmod_pvwattsv8_test.cpp
Labels: pv

#932 Accommodate one-axis tilt flipping convention
  shared/lib_irradproc.cpp
  shared/lib_irradproc.h
Labels: bug

#936 Ssc 847 transformer loss fix
  shared/lib_battery_dispatch.cpp
  shared/lib_battery_powerflow.cpp
  shared/lib_battery_powerflow.h
  shared/lib_power_electronics.cpp
  shared/lib_power_electronics.h
  ssc/cmod_battery.cpp
  ssc/cmod_battery.h
  ssc/cmod_pvsamv1.cpp
  ssc/cmod_pvsamv1.h
  test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp
  test/shared_test/lib_battery_powerflow_test.cpp
  test/ssc_test/cmod_battery_pvsamv1_test.cpp
Labels: bug, battery

#941 Fix rollover issues in bill w/o system
  ssc/cmod_utilityrate5.cpp
  test/ssc_test/cmod_utilityrate5_test.cpp
Labels: bug, utility rate

#940 Remove extraneous i==1 from cashloan. Also correct typo in comments to issue number (1038)
  ssc/cmod_cashloan.cpp
  ssc/cmod_communitysolar.cpp
  ssc/cmod_equpartflip.cpp
  ssc/cmod_host_developer.cpp
  ssc/cmod_ippppa.cpp
  ssc/cmod_levpartflip.cpp
  ssc/cmod_merchantplant.cpp
  ssc/cmod_saleleaseback.cpp
  ssc/cmod_singleowner.cpp
  ssc/common.cpp
Labels: bug, financial
