Repository NREL/ssc, pull requests merged in 2023-01, with the labels that each got.

#965 Add PTES Design Point Dialog Widget
  samples/PTES_lk/ptes_design_point.lk
  ssc/CMakeLists.txt
  ssc/cmod_ptes_design_point.cpp
  ssc/sscapi.cpp
  tcs/CMakeLists.txt
  tcs/ptes_solver_design_point.cpp
  tcs/ptes_solver_design_point.h
Labels: csp

#967 Fix and add htf props
  tcs/htf_props.cpp
  tcs/htf_props.h
Labels: csp

#975 Enable solar_resource_data in the trough models
  ssc/cmod_trough_physical.cpp
  ssc/cmod_trough_physical_iph.cpp
Labels: bug

#960 Sandia clearance height
  shared/lib_pv_io_manager.cpp
Labels: bug

#963 Remove unused lifetime load output for non-lifetime projects
  ssc/cmod_utilityrate5.cpp
Labels: bug, pv

#978 Fix rear shading and soiling issue
  shared/lib_irradproc.cpp
  ssc/cmod_pvsamv1.cpp
Labels: bug

#982 Fix field freeze protection calculation when startup time is zero
  tcs/csp_solver_trough_collector_receiver.cpp
Labels: bug

#979 Ensure key variables in the powerflow code have a minimum of zero
  shared/lib_battery_powerflow.cpp
Labels: bug, battery

#985 Support WIND Toolkit CSV format
  shared/lib_windfile.cpp
  shared/lib_windfile.h
  shared/lib_windwatts.cpp
  ssc/cmod_windfile.cpp
  ssc/cmod_windpower.cpp
  test/input_docs/wind.srw
  test/input_docs/wind_30m.srw
  test/input_docs/wind_leapYear.srw
Labels: enhancement, requires SAM Help revision
