Repository NREL/ssc, pull requests merged in 2024-02, with the labels that each got.

#1125 Fix reporting of ground reflected rear irradiance gains in loss diagram
  shared/lib_irradproc.cpp
  shared/lib_irradproc.h
Labels: bug, pv

#1126 Use calculated DNI for Allen method when there is no DNI in weather file
  ssc/cmod_pvsamv1.cpp
Labels: bug, pv

#1127 Set upper limit of one for diffuse sky shading non-linear factor
  shared/lib_pvshade.cpp
Labels: bug, pv

#1135 Fix subhourly indexing error in retail rate dispatch forecast function
  shared/lib_utility_rate_equations.cpp
  test/shared_test/lib_utility_rate_equations_test.cpp
Labels: bug, battery

#1128 Expose snow slide coefficient in ssc
  shared/lib_pv_io_manager.cpp
  shared/lib_snowmodel.cpp
  shared/lib_snowmodel.h
  ssc/cmod_pvsamv1.cpp
  ssc/cmod_pvwattsv7.cpp
  ssc/cmod_pvwattsv8.cpp
  ssc/cmod_snowmodel.cpp
Labels: enhancement, pv

#1138 Improve batt temp timestep message
  ssc/cmod_battery.cpp
Labels: bug

#1140 Time zone fix for NSRDB MSG V1.0.0
  shared/lib_weatherfile.cpp
Labels: new feature
