Repository NREL/ssc, pull requests merged in 2025-04, with the labels that each got.

#1303 Retail rates dispatch grid export
  .github/workflows/ci.yml
  shared/lib_battery_dispatch.cpp
  shared/lib_battery_dispatch.h
  shared/lib_battery_dispatch_automatic_btm.cpp
  shared/lib_utility_rate_equations.cpp
  test/main.cpp
  test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp
  test/ssc_test/cmod_battery_pvsamv1_test.cpp
Labels: enhancement, battery, requires SAM Help revision

#1311 Remove bifacial messages for one-axis tracking
  ssc/cmod_pvsamv1.cpp
  ssc/cmod_pvwattsv8.cpp
Labels: pv

#1312 Fix minor bugs in packed bed TES model.
  tcs/csp_solver_packedbed_tes.cpp
Labels: bug, csp

#1318 Fix cashloan IRR units (% not $)
  ssc/cmod_cashloan.cpp
Labels: bug

#1317 Remove wind file elevation check
  shared/lib_windfile.cpp
Labels: dev bug
